# Generated by Django 4.1 on 2024-01-02 11:56

from django.db import migrations, models
import django.db.models.deletion
import warehouse_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupier_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('turning_day', models.IntegerField(validators=[warehouse_project.models.validate_turning_day])),
                ('payment_method', models.BooleanField()),
                ('debt', models.BigIntegerField()),
                ('refreshed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.IntegerField(validators=[warehouse_project.models.validate_area])),
                ('cost', models.IntegerField(validators=[warehouse_project.models.validate_cost])),
                ('comment', models.TextField()),
                ('occupier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse_project.occupier')),
            ],
        ),
    ]
