# Generated by Django 4.2.4 on 2024-01-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="occupier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse_project.occupier",
            ),
        ),
    ]
