# Generated by Django 3.2.5 on 2024-01-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_project', '0003_alter_storage_occupier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='occupier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_project.occupier'),
        ),
    ]
